# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groups',
            new_name='empgroups',
        ),
    ]
